# Generated by Django 5.1 on 2024-11-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='shipping',
            field=models.PositiveSmallIntegerField(default=8, null=True),
        ),
    ]
