# Generated by Django 5.1 on 2024-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_usedcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
